### ISSUE TITLE
importing classes and modules.

### ISSUE THREAD

**Issue by rburkhardt-csumb** [gatech-csl/jes#96]
I am not sure if JES has the ability to do this or not but if it does, how does one import nonstandard classes and modules that they create?

**Comment by mjguzdial** [comment]
We built in a function "addLibPath" that adds a function to sys.path.  Creating libraries and accessing them is described on pages 246-247 of the Python 4th Edition MediaComp book.

 - Mark


________________________________

**Comment by rburkhardt-csumb** [comment]
Thank you. I will get a copy of the book
